gui:
  language: en
  showBranchCommitHash: true
  showPanelJumps: false
  showListFooter: false
  nerdFontsVersion: "3"
  skipRewordInEditorWarning: true
  skipStashWarning: true
  scrollHeight: 3
  theme:
    selectedLineBgColor:
    - "#b6e2ff"

git:
  paging:
    colorArg: always
    pager: delta --light --paging=never

promptToReturnFromSubprocess: false

customCommands:
  - key: "<c-g>"
    context: "files"
    command: 'hub browse -- "commit/{{.SelectedLocalCommit.Hash}}"'
  - key: "<c-k>"
    context: "files"
    command: 'echo git rm {{.SelectedFile.Name | quote}}'
    prompts:
    - type: "confirm"
      title: "git rm"
      body: "Do you want to delete the selected file?"
