k9s:
  liveViewAutoRefresh: false
  screenDumpDir: /Users/timu/Library/Application Support/k9s/screen-dumps
  refreshRate: 1.5
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    splashless: true
    enableMouse: true
    headless: false
    logoless: true
    crumbsless: true
    reactive: false
    noIcons: false
    defaultsToFullScreen: false
    skin: solarized-light
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 1000
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
hotKeys:
  # Hitting Shift-0 navigates to your pod view
  blabli:
    shortCut:    "."
    description: Viewing pods
    command:     pods

